name: Build & Deploy (Backend)

on:
    push:
        branches: [main]

env:
    IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/aiclinic-backend:latest

jobs:
    build-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build & push image
              uses: docker/build-push-action@v5
              with:
                  context: . # if Dockerfile is in repo root
                  push: true
                  tags: ${{ env.IMAGE_NAME }}

    deploy:
        runs-on: ubuntu-latest
        needs: build-push
        steps:
            - name: Deploy to backend droplet
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.DO_BACK_HOST }}
                  username: ${{ secrets.DO_BACK_USER }}
                  password: ${{ secrets.DO_BACK_PASS }}
                  envs: IMAGE_NAME
                  script: |
                      set -e


                      docker network create web || true
                      docker network connect web caddy-api || true


                      docker rm -f aiclinic-back || true
                      docker pull $IMAGE_NAME
                      docker run -d --name aiclinic-back \
                        --restart always \
                        --network web \
                        $IMAGE_NAME
